apiVersion: v1
data:
  APOLLO_API_KEY: bi1JOWVIY2txbW5VUnpFMVprODJ4Zw==
  GONG_ACCESS_KEY: VFYzM0JQWjVVTjQ1UUtaQ1oyVUNBS1JYSFE2UTNMNU4=
  GONG_ACCESS_KEY_SECRET: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKbGVIQWlPakl3TlRReE5UQTRPRFVzSW1GalkyVnpjMHRsZVNJNklsUldNek5DVUZvMVZVNDBOVkZMV2tOYU1sVkRRVXRTV0VoUk5sRXpURFZPSW4wLnpnUHZEUVFJdlUxa3ZGXzljdGpjS3VxQzV4S2hscFpvN01INXY3QVl1ZlU=
  HUBSPOT_ACCESS_TOKEN: cGF0LW5hMS1jMTY3MWJlYS02NDZhLTRhNjEtYTJkYS0zM2JkMzM1MjhkYzc=
  HUBSPOT_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  HUBSPOT_CLIENT_SECRET: NjA4MDMxN2ItMTVmOS00YTczLWIxNTEtYTA3MzE2MTZjYTUw
  SALESFORCE_CLIENT_ID: Zm9vYmFy
  SALESFORCE_CLIENT_SECRET: Zm9vYmFy
  SALESFORCE_PASSWORD: Zm9vYmFy
  SALESFORCE_SECURITY_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SALESFORCE_USERNAME: Zm9vYmFy
  SLACK_APP_TOKEN: eGFwcC1SRVBMQUNFX1dJVEhfUkVBTF9TTEFDS19BUFBfVE9LRU4=
  SLACK_BOT_TOKEN: eG94Yi15b3VyLXNsYWNrLWJvdC10b2tlbg==
  SLACK_CLIENT_ID: UkVQTEFDRV9XSVRIX1JFQUxfU0xBQ0tfQ0xJRU5UX0lE
  SLACK_CLIENT_SECRET: UkVQTEFDRV9XSVRIX1JFQUxfU0xBQ0tfQ0xJRU5UX1NFQ1JFVA==
  SLACK_SIGNING_SECRET: UkVQTEFDRV9XSVRIX1JFQUxfU0xBQ0tfU0lHTklOR19TRUNSRVQ=
  TELEGRAM_BOT_TOKEN: Zm9vYmFy
  TELEGRAM_CHAT_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  USERGEMS_API_KEY: Zm9vYmFy
  ZILLOW_API_KEY: Zm9vYmFy
kind: Secret
metadata:
  labels:
    app: sophia-ai
    component: business-integrations
  name: sophia-business-secrets
  namespace: sophia
type: Opaque
