apiVersion: v1
kind: Secret
metadata:
  name: sophia-business-secrets
  namespace: sophia
  labels:
    app: sophia-ai
    component: business-integrations
type: Opaque
data:
  # HubSpot
  HUBSPOT_ACCESS_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  HUBSPOT_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  HUBSPOT_CLIENT_SECRET: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=

  # Gong
  GONG_ACCESS_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  GONG_ACCESS_KEY_SECRET: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=

  # Salesforce
  SALESFORCE_CLIENT_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SALESFORCE_CLIENT_SECRET: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SALESFORCE_USERNAME: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SALESFORCE_PASSWORD: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SALESFORCE_SECURITY_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=

  # Slack
  SLACK_APP_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SLACK_BOT_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SLACK_CLIENT_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SLACK_CLIENT_SECRET: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  SLACK_SIGNING_SECRET: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=

  # Other Integrations
  APOLLO_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  USERGEMS_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  ZILLOW_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  TELEGRAM_BOT_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=
  TELEGRAM_CHAT_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M180OTA5NDE=