apiVersion: v1
kind: Secret
metadata:
  name: sophia-infrastructure-secrets
  namespace: sophia
  labels:
    app: sophia-ai
    component: infrastructure
type: Opaque
data:
  LAMBDA_API_KEY: c2VjcmV0X3NvcGhpYWNsb3VkYXBpXzE3Y2Y3ZjNjZWRjYTQ4ZjE4YjRiOGVhNDZjYmIyNThmLkVzTFh0MGxrR2xoWjFOZDM2OUxkNURNU3VoSmc5Tzl5
  LAMBDA_PRIVATE_SSH_KEY: Zm9vYmFy
  LAMBDA_PUBLIC_SSH_KEY: Zm9vYmFy
  DNSIMPLE_ACCOUNT_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  DNSIMPLE_API_KEY: ZG5zaW1wbGVfdV9YQkhleWhIM084dUtKRjZIbnFVNzZoN0FOV2ROdlV6Tg==
  DOCKERHUB_USERNAME: Zm9vYmFy
  DOCKERHUB_PERSONAL_ACCESS_TOKEN: ZGNrcl9wYXRfaDZ5NHI4bEhMWEkzZnFPSVppdUsya3o0aC04
  GRAFANA_ADMIN_PASSWORD: Zm9vYmFy
  JWT_SECRET: Zm9vYmFy
  API_SECRET_KEY: Zm9vYmFy
  BACKUP_ENCRYPTION_KEY: Zm9vYmFy
---
apiVersion: v1
kind: Secret
metadata:
  name: sophia-github-secrets
  namespace: sophia
  labels:
    app: sophia-ai
    component: github
type: Opaque
data:
  GITHUB_APP_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  GITHUB_INSTALLATION_ID: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  GITHUB_PRIVATE_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  GH_PAT_TOKEN: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
---
apiVersion: v1
kind: Secret
metadata:
  name: sophia-research-secrets
  namespace: sophia
  labels:
    app: sophia-ai
    component: research
type: Opaque
data:
  SERPAPI_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  TAVILY_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  PERPLEXITY_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  GOOGLE_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  VOYAGE_AI_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
  COHERE_API_KEY: ZHVtbXlfdmFsdWVfZm9yX3Rlc3RpbmdfMTc1NjIzMjM5M18zMzcwNTY=
