apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: sophia-ai
type: Opaque
data:
  # OpenAI API Key for GPT models and embeddings
  OPENAI_API_KEY: "" # Fill with base64 encoded OpenAI API Key
  # XAI API Key for Grok models
  XAI_API_KEY: "" # Fill with base64 encoded XAI API Key
  # Anthropic API Key for Claude models
  ANTHROPIC_API_KEY: "" # Fill with base64 encoded Anthropic API Key
  # Google API Key for Gemini models and embeddings
  GOOGLE_API_KEY: "" # Fill with base64 encoded Google API Key
  # DeepSeek API Key for DeepSeek models
  DEEPSEEK_API_KEY: "" # Fill with base64 encoded DeepSeek API Key
  # Mistral API Key for Mistral models and embeddings
  MISTRAL_API_KEY: "" # Fill with base64 encoded Mistral API Key
  # Cohere API Key for Cohere models and embeddings
  COHERE_API_KEY: "" # Fill with base64 encoded Cohere API Key
  # Alibaba API Key for Qwen models
  ALIBABA_API_KEY: "" # Fill with base64 encoded Alibaba API Key
  # Meta API Key for Llama models
  META_API_KEY: "" # Fill with base64 encoded Meta API Key
  # Hugging Face API Key for BGE embeddings
  HUGGINGFACE_API_KEY: "" # Fill with base64 encoded Hugging Face API Key