apiVersion: v1
data:
  ANTHROPIC_API_KEY: Zm9vYmFy
  DEEPSEEK_API_KEY: Zm9vYmFy
  GROQ_API_KEY: Zm9vYmFy
  LLAMA_API_KEY: Zm9vYmFy
  MISTRAL_API_KEY: Zm9vYmFy
  OPENAI_API_KEY: Zm9vYmFy
  OPENROUTER_API_KEY: Zm9vYmFy
  PORTKEY_API_KEY: Zm9vYmFy
  TOGETHERAI_API_KEY: Zm9vYmFy
  VENICE_AI_API_KEY: Zm9vYmFy
  XAI_API_KEY: Zm9vYmFy
kind: Secret
metadata:
  labels:
    app: sophia-ai
    component: llm
  name: sophia-llm-secrets
  namespace: sophia
type: Opaque
