apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cloud-config
  namespace: sophia
  labels:
    app: sophia-ai
    component: vector-database
type: Opaque
data:
  WEAVIATE_URL: aHR0cHM6Ly93NmJpZ3BveHNyd3ZxN3dsZ21tZHZhLmMwLnVzLXdlc3QzLmdjcC53ZWF2aWF0ZS5jbG91ZA==
  WEAVIATE_API_KEY: Vk1LakdNUVVuWFFJRGlGT2NpWlpPaHI3YW1CZkNITWg3aE5m
  WEAVIATE_GRPC_URL: Z3JwYy13NmJpZ3BveHNyd3ZxN3dsZ21tZHZhLmMwLnVzLXdlc3QzLmdjcC53ZWF2aWF0ZS5jbG91ZDo0NDM=