app = "sophiaai-mcp-research-v2"
primary_region = "ord"

[env]
  PORT = "8080"
  DEFAULT_LLM_MODEL = "gpt-5"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

  [[http_service.checks]]
    method = "POST"
    path = "/search"
    interval = "60s"
    timeout = "10s"
    grace_period = "120s"
    headers = { "Content-Type" = "application/json" }
    body = '{"query": "health check", "max_results": 1}'

