app = "sophiaai-mcp-research-v2"
primary_region = "ord"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"
  DEFAULT_LLM_MODEL = "gpt-5"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 75

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

  [[http_service.checks]]
    method = "POST"
    path = "/search"
    interval = "60s"
    timeout = "10s"
    grace_period = "120s"
    headers = { "Content-Type" = "application/json" }
    body = '{"query": "health check", "max_results": 1}'

[experimental]
  auto_rollback = true

