apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: sophia-ai
spec:
  template:
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.7.0
        env:
        - name: MALLOC_ARENA_MAX
          value: "0"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
