apiVersion: v1
kind: Service
metadata:
  name: cert-manager-acme-challenge
  namespace: sophia
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app: cert-manager-acme-challenge

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-acme-challenge
  namespace: sophia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-acme-challenge
  template:
    metadata:
      labels:
        app: cert-manager-acme-challenge
    spec:
      containers:
        - name: acme-challenge
          image: nginx:alpine
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: challenge-data
              mountPath: /usr/share/nginx/html/.well-known/acme-challenge/
      volumes:
        - name: challenge-data
          emptyDir: {}