apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-slack
  namespace: sophia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-slack
  template:
    metadata:
      labels:
        app: mcp-slack
    spec:
      containers:
      - name: mcp-slack
        image: localhost:5000/sophia-slack:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: SLACK_BOT_TOKEN
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: SLACK_SIGNING_SECRET
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: sophia-config
              key: tenant
        resources:
          requests:
            cpu: 100m
            memory: "128Mi"
          limits:
            cpu: 500m
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-slack
  namespace: sophia
spec:
  selector:
    app: mcp-slack
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP