apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-research
  namespace: sophia
  labels:
    app: mcp-research
    component: backend
    service: research
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-research
  template:
    metadata:
      labels:
        app: mcp-research
        component: backend
        service: research
    spec:
      containers:
      - name: mcp-research
        image: localhost:5000/sophia-research:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DEFAULT_LLM_MODEL
          value: "gpt-4"
        - name: TENANT
          value: "pay-ready"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: OPENAI_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: TAVILY_API_KEY
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: PERPLEXITY_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: OPENROUTER_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: REDIS_URL
        - name: NEON_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: NEON_DATABASE_URL
        - name: QDRANT_URL
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: QDRANT_URL
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: QDRANT_API_KEY
        resources:
          limits:
            cpu: 1
            memory: "2Gi"
          requests:
            cpu: 500m
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: research-storage
          mountPath: /data
      volumes:
      - name: research-storage
        persistentVolumeClaim:
          claimName: mcp-research-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-research
  namespace: sophia
  labels:
    app: mcp-research
    component: backend
    service: research
spec:
  type: ClusterIP
  selector:
    app: mcp-research
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
