apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-agents
  namespace: sophia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-agents
  template:
    metadata:
      labels:
        app: mcp-agents
    spec:
      containers:
      - name: mcp-agents
        image: sophia-ai-intel-1-sophia-agents:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        env:
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: OPENROUTER_API_KEY
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MCP_MODE
          value: "production"
        resources:
          requests:
            cpu: 500m
            memory: "1Gi"
          limits:
            cpu: 1
            memory: "2Gi"
        volumeMounts:
        - name: agents-storage
          mountPath: /data
      volumes:
      - name: agents-storage
        emptyDir: {}
      imagePullSecrets:
      - name: github-registry
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-agents
  namespace: sophia
spec:
  selector:
    app: mcp-agents
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP