apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-agents
  namespace: sophia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-agents
  template:
    metadata:
      labels:
        app: mcp-agents
    spec:
      containers:
      - name: mcp-agents
        image: localhost:5000/sophia-agents:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        # Health probes for mcp-agents
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        # Startup probe for slower services
        startupProbe:
          httpGet:
            path: /health/live
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30  # Allow up to 150 seconds for startup
        env:
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-llm-secrets
              key: OPENROUTER_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-redis-secrets
              key: REDIS_URL
        - name: MCP_MODE
          value: "production"
        resources:
          requests:
            cpu: 500m
            memory: "1Gi"
          limits:
            cpu: 1
            memory: "2Gi"
        volumeMounts:
        - name: agents-storage
          mountPath: /data
      volumes:
      - name: agents-storage
        persistentVolumeClaim:
          claimName: mcp-agents-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-agents
  namespace: sophia
spec:
  selector:
    app: mcp-agents
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
