apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: sophia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: ghcr.io/ai-cherry/sophia-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-redis-secrets
              key: REDIS_URL
        - name: MCP_RESEARCH_URL
          value: "http://mcp-research:8080"
        - name: MCP_CONTEXT_URL
          value: "http://mcp-context:8080"
        - name: MCP_AGENTS_URL
          value: "http://mcp-agents:8002"
        - name: MCP_HUBSPOT_URL
          value: "http://mcp-hubspot:8004"
        - name: MCP_GITHUB_URL
          value: "http://mcp-github:8005"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: 1
            memory: "2Gi"
          limits:
            cpu: 2
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: github-registry
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: sophia
spec:
  selector:
    app: orchestrator
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
