apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-lambda
  namespace: sophia
  labels:
    app: sophia-lambda
    component: lambda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophia-lambda
  template:
    metadata:
      labels:
        app: sophia-lambda
        component: lambda
    spec:
      containers:
      - name: sophia-lambda
        image: sophia-ai-intel-1-sophia-lambda:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: TENANT
          value: "pay-ready"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-lambda
  namespace: sophia
  labels:
    app: sophia-lambda
    component: lambda
spec:
  type: ClusterIP
  selector:
    app: sophia-lambda
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http