apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-business
  namespace: sophia
  labels:
    app: sophia-business
    component: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophia-business
  template:
    metadata:
      labels:
        app: sophia-business
        component: business
    spec:
      containers:
      - name: sophia-business
        image: sophia-ai-intel-1-sophia-business:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: TENANT
          value: "pay-ready"
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-business
  namespace: sophia
  labels:
    app: sophia-business
    component: business
spec:
  type: ClusterIP
  selector:
    app: sophia-business
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http