# Sophia AI Intel - MCP Context Service
app = "sophiaai-mcp-context"
primary_region = "ord"

[build]
  dockerfile = "services/mcp-context/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DEFAULT_LLM_MODEL = "gpt-5"

# Secrets are managed via Fly.io secrets (already populated)
# fly secrets set NEON_DATABASE_URL=xxx PORTKEY_API_KEY=xxx -a sophiaai-mcp-context

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

  [[http_service.checks]]
    method = "GET"
    path = "/context/stats"
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Multi-region for high availability
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
  region = "sjc"

