# Sophia AI Intel - MCP GitHub Service
app = "sophiaai-mcp-github"
primary_region = "ord"

[build]
  dockerfile = "services/mcp-github/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DEFAULT_LLM_MODEL = "gpt-5"

# Secrets are managed via Fly.io secrets (already populated)
# fly secrets set GITHUB_APP_ID=xxx GITHUB_INSTALLATION_ID=xxx GITHUB_PRIVATE_KEY=xxx -a sophiaai-mcp-github

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

  [[http_service.checks]]
    method = "GET"
    path = "/repo/info?owner=ai-cherry&repo=sophia-ai-intel"
    interval = "60s"
    timeout = "10s"
    grace_period = "120s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Single region initially (read-only service)
[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  region = "sjc"

