# Sophia AI Intel - MCP Research Service
app = "sophiaai-mcp-research"
primary_region = "ord"

[build]
  dockerfile = "services/mcp-research/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DEFAULT_LLM_MODEL = "gpt-5"

# Secrets are managed via Fly.io secrets (already populated)
# fly secrets set PORTKEY_API_KEY=xxx TAVILY_API_KEY=xxx SERPER_API_KEY=xxx -a sophiaai-mcp-research

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

  [[http_service.checks]]
    method = "POST"
    path = "/search"
    interval = "60s"
    timeout = "10s"
    grace_period = "120s"
    headers = { "Content-Type" = "application/json" }
    body = '{"query": "health check", "max_results": 1}'

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Multi-region for high availability
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
  region = "sjc"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
  region = "ewr"

