global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker service discovery for all Sophia AI services
  - job_name: 'sophia-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: service_name
      - source_labels: [__meta_docker_container_label_prometheus_io_port]
        target_label: __meta_docker_port
        action: replace
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        target_label: __metrics_path__
        action: replace
      - target_label: __address__
        replacement: $1:$2
        source_labels: [__meta_docker_container_name, __meta_docker_port]
        separator: ':'
    scrape_interval: 10s
    metrics_path: '/metrics'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis metrics (if Redis exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Qdrant metrics (if available)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s