server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'service_name'
      - action: labelmap
        regex: '__meta_docker_container_label_(.+)'
      - source_labels: ['__meta_docker_container_name']
        regex: 'sophia-(.+)'
        target_label: 'service'
        replacement: '$1'

  # System logs
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/*.log
    pipeline_stages:
      - match:
          selector: '{job="system-logs"}'
          stages:
            - multiline:
                firstline: '^\w{3} \d{2} \d{2}:\d{2}:\d{2}'
                max_lines: 1000
            - regex:
                expression: '^(?P<timestamp>\w{3} \d{2} \d{2}:\d{2}:\d{2}) (?P<hostname>\w+) (?P<service>\w+)\[(?P<pid>\d+)\]: (?P<message>.*)$'
            - labels:
                timestamp:
                hostname:
                service:
                pid:
            - timestamp:
                source: timestamp
                format: 'Jan _2 15:04:05'
                location: 'UTC'

  # Application specific logs
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application-logs
          service: sophia
          __path__: /var/log/sophia/*.log
    pipeline_stages:
      - match:
          selector: '{job="application-logs"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
                  service: service
                  timestamp: timestamp
            - labels:
                level:
                service:
            - timestamp:
                source: timestamp
                format: '2006-01-02T15:04:05Z'
                location: 'UTC'