name: Lambda Operations (Reusable)
on:
  workflow_call:
    inputs:
      action: {required: true, type: string}
      payload: {required: false, type: string, default: '{}'}
    secrets:
      LAMBDA_LABS_API_KEY: {required: false}
      LAMBDA_API_CLOUD_ENDPOINT: {required: false}
      LAMBDA_SSH_PRIVATE_KEY: {required: false}
jobs:
  lambda-operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p proofs/lambda
      - run: |
          if [ -z "${{ secrets.LAMBDA_LABS_API_KEY }}" ]; then
            echo '{"status": "failure", "errors": [{"provider": "lambda", "code": "not-configured", "message": "Lambda Labs API not configured"}]}' > proofs/lambda/not_configured.json
          else
            echo '{"status": "failure", "errors": [{"provider": "lambda", "code": "not-implemented", "message": "Lambda operations need implementation"}]}' > proofs/lambda/not_implemented.json
          fi
      - run: git config user.name "sophia-bot" && git config user.email "sophia-bot@users.noreply.github.com" && git add proofs/lambda/ && git commit -m "[proof] lambda/${{ inputs.action }}: completed" || true && git push || true
