name: Mem0 Operations (Reusable)
on:
  workflow_call:
    inputs:
      action: {required: true, type: string}
      payload: {required: false, type: string, default: '{}'}
    secrets:
      MEM0_API_KEY: {required: false}
jobs:
  mem0-operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p proofs/mem0
      - run: |
          if [ -z "${{ secrets.MEM0_API_KEY }}" ]; then
            echo '{"status": "failure", "errors": [{"provider": "mem0", "code": "not-configured", "message": "MEM0_API_KEY not set"}]}' > proofs/mem0/not_configured.json
          else
            echo '{"status": "failure", "errors": [{"provider": "mem0", "code": "not-implemented", "message": "Mem0 operations need implementation"}]}' > proofs/mem0/not_implemented.json
          fi
      - run: |
          git config user.name "sophia-bot" && git config user.email "sophia-bot@users.noreply.github.com"
          git add proofs/mem0/ && git commit -m "[proof] mem0/${{ inputs.action }}: completed" || true && git push || true
