name: Slack Operations (Reusable)
on:
  workflow_call:
    inputs:
      action: {required: true, type: string}
      payload: {required: false, type: string, default: '{}'}
    secrets:
      SLACK_BOT_TOKEN: {required: false}
      SLACK_SIGNING_SECRET: {required: false}
      SLACK_APP_TOKEN: {required: false}
jobs:
  slack-operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p proofs/slack
      - run: |
          if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
            echo '{"status": "failure", "errors": [{"provider": "slack", "code": "not-configured", "message": "SLACK_BOT_TOKEN not set"}]}' > proofs/slack/not_configured.json
          else
            echo '{"status": "failure", "errors": [{"provider": "slack", "code": "not-implemented", "message": "Slack operations need implementation"}]}' > proofs/slack/not_implemented.json
          fi
      - run: |
          git config user.name "sophia-bot" && git config user.email "sophia-bot@users.noreply.github.com"
          git add proofs/slack/ && git commit -m "[proof] slack/${{ inputs.action }}: completed" || true && git push || true
