apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-mcp
  namespace: sophia-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-mcp
  template:
    metadata:
      labels:
        app: analytics-mcp
    spec:
      containers:
      - name: analytics-mcp
        image: ghcr.io/sophia-ai/analytics-mcp:latest
        ports:
        - containerPort: 8000
        env:
        - name: NEON_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neon-credentials
              key: database-url
        - name: JWT_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: jwt-public-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-mcp
  namespace: sophia-platform
spec:
  selector:
    app: analytics-mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-mcp-hpa
  namespace: sophia-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-mcp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80