app = "sophiaai-jobs-v2"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["http", "tls"]

[services.concurrency]
  type = "requests"
  soft_limit = 50
  hard_limit = 75

[[services.http_checks]]
  method = "GET"
  path = "/healthz"
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"

[env]
  JOBS_ENVIRONMENT = "production"
  TENANT = "pay-ready"
  
# Scheduled machine configuration for hourly reindex
[[machines]]
  role = "scheduled"
  schedule = "0 */1 * * *"  # Every hour
  process = "reindex"
  cmd = ["python", "/app/reindex.py"]
  
[machines.vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  
[machines.restart]
  policy = "never"  # One-shot execution

[machines.checks]
  # No health checks needed for scheduled jobs

[experimental]
  auto_rollback = true