app = "sophiaai-jobs-v2"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# No HTTP services needed - this is a scheduled job only

[processes]
  reindex = "python reindex.py"

[env]
  JOBS_ENVIRONMENT = "production"
  TENANT = "pay-ready"
  
# Scheduled machine configuration for hourly reindex
[[machines]]
  role = "scheduled"
  schedule = "0 */1 * * *"  # Every hour
  process = "reindex"
  cmd = ["python", "/app/reindex.py"]
  
[machines.vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  
[machines.restart]
  policy = "never"  # One-shot execution

[machines.checks]
  # No health checks needed for scheduled jobs

[experimental]
  auto_rollback = true
