app = "sophia-context-api"
primary_region = "iad"

[build]
  dockerfile = "mcp/context-api/Dockerfile"
  context = "."

[env]
  PORT = "8080"
  SERVICE_NAME = "context-api"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[deploy]
  strategy = "rolling"

[[vm]]
  memory = "1gb"
  cpus = 2