app = "sophia-mcp-platform"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../../Dockerfile.multi"

[env]
  PORT = "8000"
  NODE_ENV = "production"
  LOG_LEVEL = "info"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  
  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
  
  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

[mounts]
  source = "sophia_data"
  destination = "/data"