#!/bin/bash

echo "🔐 PERMANENT GITHUB PERMISSIONS FIX"
echo "===================================="
echo ""
echo "This script will help you fix GitHub permissions permanently."
echo ""

# Check current setup
echo "📊 CURRENT SETUP ANALYSIS:"
echo "- Current remote URL: $(git remote get-url origin)"
echo "- Current user: $(git config user.name) ($(git config user.email))"
echo ""

echo "🚨 IDENTIFIED ISSUES:"
echo "1. GitHub token likely expired or insufficient scopes"
echo "2. Token embedded in remote URL (security risk)"
echo "3. Missing workflow dispatch permissions"
echo ""

echo "🎯 PERMANENT SOLUTION STEPS:"
echo ""
echo "STEP 1: GENERATE NEW GITHUB PERSONAL ACCESS TOKEN"
echo "================================================"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Name: 'Sophia AI Intel Deployment Token'"
echo "4. Expiration: 'No expiration' (or 90 days minimum)"
echo "5. Select these scopes:"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ workflow (Update GitHub Action workflows)" 
echo "   ✅ write:packages (Upload packages to GitHub Package Registry)"
echo "   ✅ read:org (Read org and team membership, read org projects)"
echo "6. Click 'Generate token'"
echo "7. COPY THE TOKEN (you won't see it again!)"
echo ""

echo "STEP 2: UPDATE GIT CONFIGURATION"
echo "================================"
echo "Run these commands with your new token:"
echo ""
echo "# Replace YOUR_NEW_TOKEN with the token you just generated"
echo "git remote set-url origin https://YOUR_NEW_TOKEN@github.com/ai-cherry/sophia-ai-intel.git"
echo ""
echo "# OR use SSH instead (more secure):"
echo "git remote set-url origin git@github.com:ai-cherry/sophia-ai-intel.git"
echo ""

echo "STEP 3: TEST ACCESS"
echo "=================="
echo "git push --dry-run"
echo ""

echo "STEP 4: DEPLOY FIXES"
echo "==================="
echo "git push"
echo ""

echo "🔒 SECURITY BEST PRACTICES:"
echo "============================"
echo "1. Use SSH keys instead of tokens when possible"
echo "2. Set token expiration (90 days max)"
echo "3. Regularly rotate tokens"
echo "4. Use GitHub App tokens for production"
echo "5. Store tokens in environment variables, not in URLs"
echo ""

echo "🚀 ALTERNATIVE: GITHUB CLI METHOD"
echo "=================================="
echo "If you have GitHub CLI installed:"
echo "gh auth login"
echo "git remote set-url origin https://github.com/ai-cherry/sophia-ai-intel.git"
echo "# GitHub CLI will handle authentication automatically"
echo ""

read -p "Press Enter to continue..."
