apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-ai-core
  namespace: sophia
  labels:
    app: sophia-ai-core
    tier: ai-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sophia-ai-core
  template:
    metadata:
      labels:
        app: sophia-ai-core
        tier: ai-services
    spec:
      containers:
      - name: sophia-ai-core
        image: sophia-registry/sophia-ai-core:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # Health probes for consolidated AI services
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30  # Allow up to 300 seconds for ML model loading
        env:
        - name: SERVICE_NAME
          value: "sophia-ai-core"
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-llm-secrets
              key: OPENROUTER_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-llm-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-llm-secrets
              key: OPENAI_API_KEY
        - name: WEAVIATE_URL
          valueFrom:
            secretKeyRef:
              name: sophia-database-secrets
              key: WEAVIATE_URL
        - name: WEAVIATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-database-secrets
              key: WEAVIATE_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-redis-secrets
              key: REDIS_URL
        - name: MODE
          value: "production"
        resources:
          requests:
            cpu: 1
            memory: "2Gi"
          limits:
            cpu: 2
            memory: "4Gi"
        volumeMounts:
        - name: ai-storage
          mountPath: /data
        - name: models-cache
          mountPath: /app/.cache
      volumes:
      - name: ai-storage
        persistentVolumeClaim:
          claimName: sophia-ai-core-storage
      - name: models-cache
        emptyDir:
          sizeLimit: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-ai-core
  namespace: sophia
  labels:
    app: sophia-ai-core
    tier: ai-services
spec:
  selector:
    app: sophia-ai-core
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sophia-ai-core-storage
  namespace: sophia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi