apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-communications
  namespace: sophia
  labels:
    app: sophia-communications
    tier: communication-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophia-communications
  template:
    metadata:
      labels:
        app: sophia-communications
        tier: communication-services
    spec:
      containers:
      - name: sophia-communications
        image: sophia-registry/sophia-communications:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 15
        env:
        - name: SERVICE_NAME
          value: "sophia-communications"
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: sophia-communication-secrets
              key: SLACK_BOT_TOKEN
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: sophia-communication-secrets
              key: SLACK_APP_TOKEN
        - name: GONG_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-communication-secrets
              key: GONG_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-redis-secrets
              key: REDIS_URL
        - name: MODE
          value: "production"
        resources:
          requests:
            cpu: 300m
            memory: "512Mi"
          limits:
            cpu: 800m
            memory: "1Gi"
        volumeMounts:
        - name: comm-storage
          mountPath: /data
      volumes:
      - name: comm-storage
        persistentVolumeClaim:
          claimName: sophia-communications-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-communications
  namespace: sophia
  labels:
    app: sophia-communications
    tier: communication-services
spec:
  selector:
    app: sophia-communications
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sophia-communications-storage
  namespace: sophia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi