apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-business-intel
  namespace: sophia
  labels:
    app: sophia-business-intel
    tier: business-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sophia-business-intel
  template:
    metadata:
      labels:
        app: sophia-business-intel
        tier: business-services
    spec:
      containers:
      - name: sophia-business-intel
        image: sophia-registry/sophia-business-intel:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 20
        env:
        - name: SERVICE_NAME
          value: "sophia-business-intel"
        - name: SALESFORCE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: sophia-business-secrets
              key: SALESFORCE_CLIENT_ID
        - name: SALESFORCE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: sophia-business-secrets
              key: SALESFORCE_CLIENT_SECRET
        - name: HUBSPOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-business-secrets
              key: HUBSPOT_API_KEY
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: sophia-database-secrets
              key: POSTGRES_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sophia-redis-secrets
              key: REDIS_URL
        - name: MODE
          value: "production"
        resources:
          requests:
            cpu: 500m
            memory: "1Gi"
          limits:
            cpu: 1
            memory: "2Gi"
        volumeMounts:
        - name: business-storage
          mountPath: /data
      volumes:
      - name: business-storage
        persistentVolumeClaim:
          claimName: sophia-business-intel-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-business-intel
  namespace: sophia
  labels:
    app: sophia-business-intel
    tier: business-services
spec:
  selector:
    app: sophia-business-intel
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sophia-business-intel-storage
  namespace: sophia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi