name: Deploy to Lambda Labs (Pulumi)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      # Add any other secrets you need here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Install Python dependencies
        run: |
          cd ops/pulumi
          pip install -r requirements.txt

      - name: Select or create Pulumi stack
        run: |
          cd ops/pulumi
          pulumi stack select production || pulumi stack init production

      - name: Set Pulumi config values
        working-directory: ops/pulumi
        run: |
          pulumi config set lambda-api-key "${{ secrets.LAMBDA_API_KEY }}" --secret
          pulumi config set lambda-private-ssh-key "${{ secrets.LAMBDA_PRIVATE_SSH_KEY }}" --secret
          pulumi config set lambda-public-ssh-key "${{ secrets.LAMBDA_PUBLIC_SSH_KEY }}"
          pulumi config set neon-database-url "${{ secrets.NEON_DATABASE_URL }}" --secret
          pulumi config set redis-url "${{ secrets.REDIS_URL }}" --secret
          pulumi config set openai-api-key "${{ secrets.OPENAI_API_KEY }}" --secret
          
      - name: Pulumi up (deploy)
        working-directory: ops/pulumi
        run: pulumi up --yes
