app = "sophiaai-mcp-repo"
primary_region = "ord"

[env]
  PORT = "8080"
  GITHUB_REPO = "ai-cherry/sophia-ai-intel"
  DASHBOARD_ORIGIN = "https://sophiaai-dashboard.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"

