app = "sophiaai-mcp-repo-v2"
primary_region = "ord"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"
  GITHUB_REPO = "ai-cherry/sophia-ai-intel"
  DASHBOARD_ORIGIN = "https://sophiaai-dashboard-v2.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 75

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[experimental]
  auto_rollback = true

